model: GradientBoostingClassifier

search_space:
  learning_rate: [0.01, 0.05, 0.1]
  n_estimators: [50, 100, 200 ]
  max_depth: [3, 5, 7]
  # max_iter: [100, 200, 300]
  # max_leaf_nodes: [5, 20, 30]
  # max_depth: [3, 5, 7]
  # min_samples_leaf: [1, 2, 4]
  # tol: [0.001, 0.0001, 0.00001]

search:
  type: random
  n_trials: 3


dataset: "data_test.csv" # be careful, it is a relative path to the root of the project